# Generated by Django 3.1.7 on 2021-06-09 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tagapp', '0002_auto_20210609_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.AddField(
            model_name='article',
            name='keyword',
            field=models.CharField(default='', max_length=300),
        ),
    ]
