# Generated by Django 3.1.7 on 2021-06-09 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tagapp', '0004_article_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
    ]
