# Generated by Django 3.1.7 on 2021-06-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tagapp', '0006_article_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
