# Generated by Django 3.1.7 on 2021-06-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tagapp', '0007_auto_20210609_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='wikidata_url',
        ),
        migrations.AddField(
            model_name='tag',
            name='aliases',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='wiki_id',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
