# Generated by Django 3.1.7 on 2021-06-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tagapp', '0007_auto_20210603_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_title',
            field=models.TextField(max_length=511),
        ),
        migrations.AlterField(
            model_name='article',
            name='journal_title',
            field=models.CharField(max_length=255),
        ),
        migrations.RemoveField(
            model_name='article',
            name='related_keywords',
        ),
        migrations.AddField(
            model_name='article',
            name='related_keywords',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
