# Generated by Django 3.1.7 on 2021-06-10 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tagapp', '0009_article_search_vector'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='search',
            new_name='search_vector',
        ),
    ]
