# Generated by Django 3.1.7 on 2021-06-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tagapp', '0010_auto_20210610_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='abstract',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='journal_title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='keyword',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='pm_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='full_name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='relatedkeywords',
            name='related_keywords',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tag',
            name='wiki_id',
            field=models.TextField(max_length=64, null=True),
        ),
    ]
