# Generated by Django 3.1.7 on 2021-06-12 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tagapp', '0013_auto_20210612_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='doi',
            field=models.TextField(null=True),
        ),
    ]
